In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("sales_data.csv")

In [5]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [17]:
df.tail()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [18]:
df.shape

(1000, 14)

In [19]:
df.columns

Index(['Product_ID', 'Sale_Date', 'Sales_Rep', 'Region', 'Sales_Amount',
       'Quantity_Sold', 'Product_Category', 'Unit_Cost', 'Unit_Price',
       'Customer_Type', 'Discount', 'Payment_Method', 'Sales_Channel',
       'Region_and_Sales_Rep'],
      dtype='str')

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   str
 2   Sales_Rep             1000 non-null   str
 3   Region                1000 non-null   str
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   str
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   str
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   str
 12  Sales_Channel         1000 non-null   str
 13  Region_and_Sales_Rep  1000 non-null   str
dtypes: float64(4), int64(2), str(8)
memory usage: 109.5 KB

In [21]:
df.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,5019.265230,25.355000,2475.304550,2728.440120,0.15239
std,29.573505,2846.790126,14.159006,1417.872546,1419.399839,0.08720
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,9989.040000,49.000000,4995.300000,5442.150000,0.30000

In [22]:
print("Regions:")
print(df['Region'].unique())

print("\nSales Representatives:")
print(df['Sales_Rep'].unique())

print("\nProduct Categories:")
print(df['Product_Category'].unique())

print("\nCustomer Types:")
print(df['Customer_Type'].unique())

print("\nPayment Methods:")
print(df['Payment_Method'].unique())

print("\nSales Channels:")
print(df['Sales_Channel'].unique())

Regions:
<StringArray>
['North', 'West', 'South', 'East']
Length: 4, dtype: str

Sales Representatives:
<StringArray>
['Bob', 'David', 'Charlie', 'Eve', 'Alice']
Length: 5, dtype: str

Product Categories:
<StringArray>
['Furniture', 'Food', 'Clothing', 'Electronics']
Length: 4, dtype: str

Customer Types:
<StringArray>
['Returning', 'New']
Length: 2, dtype: str

Payment Methods:
<StringArray>
['Cash', 'Bank Transfer', 'Credit Card']
Length: 3, dtype: str

Sales Channels:
<StringArray>
['Online', 'Retail']
Length: 2, dtype: str

In [23]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [26]:
df.dtypes

Product_ID                int64
Sale_Date                   str
Sales_Rep                   str
Region                      str
Sales_Amount            float64
Quantity_Sold             int64
Product_Category            str
Unit_Cost               float64
Unit_Price              float64
Customer_Type               str
Discount                float64
Payment_Method              str
Sales_Channel               str
Region_and_Sales_Rep        str
dtype: object

In [27]:
df['Sale_Date'] = pd.to_datetime(df['Sale_Date'])

In [28]:
df.dtypes

Product_ID                       int64
Sale_Date               datetime64[us]
Sales_Rep                          str
Region                             str
Sales_Amount                   float64
Quantity_Sold                    int64
Product_Category                   str
Unit_Cost                      float64
Unit_Price                     float64
Customer_Type                      str
Discount                       float64
Payment_Method                     str
Sales_Channel                      str
Region_and_Sales_Rep               str
dtype: object

In [36]:
#Check invalid/negative values
(df['Quantity_Sold'] < 0).sum()
(df['Sales_Amount'] < 0).sum()
(df['Unit_Cost'] < 0).sum()
(df['Unit_Price'] < 0).sum()

np.int64(0)

In [37]:
df[['Sales_Amount', 'Quantity_Sold', 'Unit_Price']].head()
#for calculating revenue

   Sales_Amount  Quantity_Sold  Unit_Price
0       5053.97             18      267.22
1       4384.02             17     4209.44
2       4631.23             30      371.40
3       2167.94             39     4467.75
4       3750.20             13      692.71

In [39]:
#Calculate estimated profit
df['Total_Cost'] = df['Unit_Cost'] * df['Quantity_Sold']
df['Profit'] = df['Sales_Amount'] - df['Total_Cost']
df[['Sales_Amount', 'Total_Cost', 'Profit']].head()

   Sales_Amount  Total_Cost     Profit
0       5053.97     2749.50    2304.47
1       4384.02    64878.63  -60494.61
2       4631.23     7846.80   -3215.57
3       2167.94   168871.17 -166703.23
4       3750.20     8285.81   -4535.61

In [40]:
#Calculate profit margin
df['Profit_Margin'] = (df['Profit'] / df['Sales_Amount']) * 100
df[['Sales_Amount', 'Profit', 'Profit_Margin']].head()

   Sales_Amount     Profit  Profit_Margin
0       5053.97    2304.47      45.597224
1       4384.02  -60494.61   -1379.889006
2       4631.23   -3215.57     -69.432311
3       2167.94 -166703.23   -7689.476185
4       3750.20   -4535.61    -120.943150

In [42]:
#Create Year Column
df['Year'] = df['Sale_Date'].dt.year
#create month column
df['Month'] = df['Sale_Date'].dt.month
#create month name
df['Month_Name'] = df['Sale_Date'].dt.month_name()
#create Quarter
df['Quarter'] = df['Sale_Date'].dt.quarter
df[['Sale_Date', 'Year', 'Month', 'Month_Name', 'Quarter']].head()

   Sale_Date  Year  Month Month_Name  Quarter
0 2023-02-03  2023      2   February        1
1 2023-04-21  2023      4      April        2
2 2023-09-21  2023      9  September        3
3 2023-08-24  2023      8     August        3
4 2023-03-24  2023      3      March        1

In [43]:
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,...,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Total_Cost,Profit,Profit_Margin,Year,Month,Month_Name,Quarter
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,...,Cash,Online,North-Bob,2749.50,2304.47,45.597224,2023,2,February,1
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,...,Cash,Retail,West-Bob,64878.63,-60494.61,-1379.889006,2023,4,April,2
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,...,Bank Transfer,Retail,South-David,7846.80,-3215.57,-69.432311,2023,9,September,3
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,...,Credit Card,Retail,South-Bob,168871.17,-166703.23,-7689.476185,2023,8,August,3
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,...,Credit Card,Online,East-Charlie,8285.81,-4535.61,-120.943150,2023,3,March,1

In [44]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
Total_Cost              0
Profit                  0
Profit_Margin           0
Year                    0
Month                   0
Month_Name              0
Quarter                 0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.shape

(1000, 21)

In [47]:
df.to_csv("cleaned_sales_data.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!